import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ChangeEvent,
  ChangeEventHandler,
  MouseEventHandler,
  useState,
} from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

interface Details {
  name: string;
  age: number;
  gender: string;
  country: { country_id: string }[];
}

export default function Home() {
  const [name, setName] = useState<string>("");
  const [isFetching, setIsFetching] = useState<boolean>(false);
  const [details, setDetails] = useState<Details | null>(null);

  const handleInput: ChangeEventHandler<HTMLInputElement> = (
    evt: ChangeEvent<HTMLInputElement>
  ) => {
    setName(evt.target.value);
  };

  const onSubmitHandler: MouseEventHandler<HTMLButtonElement> = async () => {
    try {
      setIsFetching(true);
      const queryResp = await axios<Details>(`/api/getData?name=${name}`);
      setDetails(queryResp.data);
    } catch (err) {
      console.log(err);
    } finally {
      setIsFetching(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {details ? (
          ""
        ) : (
          <p>Please enter a name below to guess the age, gender and country</p>
        )}
        <div className={styles.formCont}>
          <input
            placeholder="Enter any name"
            value={name}
            onChange={handleInput}
          />
          <button disabled={isFetching || !name} onClick={onSubmitHandler}>
            Guess
          </button>
        </div>
        {details ? (
          <div className={styles.details}>
            <p>
              Name: <span>{details?.name}</span>
            </p>
            <p>
              Age: <span>{details?.age}</span>
            </p>
            <p>
              Gender: <span>{details?.gender}</span>
            </p>
            <p>
              Country:{" "}
              <span>
                {details?.country?.map((ele) => ele.country_id).join(",")}
              </span>
            </p>
          </div>
        ) : (
          ""
        )}
        {isFetching ? <p className={styles.msg}>fetching details ....</p> : ""}
      </main>
    </>
  );
}
